#!/usr/bin/env python3
"""Fetch Tony's GEF SF delayed neutron spectra and emit C data for SmpDelayed.cc.

Usage:
    python fetch_gef_spectra.py

Outputs:
    gef_sf_spectra.h  -- C header with SFSpectrum table for inclusion in SmpDelayed.cc
    gef_sf_spectra.json  -- raw fetched data for inspection

Source: https://github.com/tonyjnel/sf-delayed-neutron-data
"""

import json
import sys
import time
import urllib.request
import yaml

BASE = "https://raw.githubusercontent.com/tonyjnel/sf-delayed-neutron-data/main"

# Isotopes to fetch: (Z, A, label)
# Priority 1: already in SmpDelayed SF table
# Priority 2: commonly encountered in reactor/safeguards contexts
ISOTOPES = [
    # Uranium
    (92, 234, "U-234"),
    (92, 235, "U-235"),
    (92, 236, "U-236"),
    (92, 238, "U-238"),
    # Plutonium
    (94, 238, "Pu-238"),
    (94, 239, "Pu-239"),
    (94, 240, "Pu-240"),
    (94, 241, "Pu-241"),
    (94, 242, "Pu-242"),
    # Americium
    (95, 241, "Am-241"),
    (95, 243, "Am-243"),
    # Curium
    (96, 242, "Cm-242"),
    (96, 244, "Cm-244"),
    (96, 246, "Cm-246"),
    (96, 248, "Cm-248"),
    # Berkelium
    (97, 249, "Bk-249"),
    # Californium
    (98, 249, "Cf-249"),
    (98, 250, "Cf-250"),
    (98, 252, "Cf-252"),
]

NBIN = 200
BIN_WIDTH = 0.05  # MeV

def fetch_yaml(z, a):
    url = f"{BASE}/spectra/dn_spectrum_{z}_{a}_sf.yaml"
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            return yaml.safe_load(resp.read().decode())
    except Exception as e:
        print(f"  WARN: {z}_{a}: {e}", file=sys.stderr)
        return None

def fetch_all():
    results = {}
    for z, a, label in ISOTOPES:
        za = 1000 * z + a
        print(f"Fetching {label} ({za})...", flush=True)
        data = fetch_yaml(z, a)
        if data:
            spec = data.get("spectrum_per_MeV", [])
            nu_d = data.get("nu_delayed", None)
            nu_d_unc = data.get("nu_delayed_unc", None)
            mean_e = data.get("average_energy_MeV", None)
            if len(spec) == NBIN and nu_d is not None:
                results[za] = {
                    "label": label, "Z": z, "A": a,
                    "nu_d": nu_d, "nu_d_unc": nu_d_unc,
                    "mean_E_MeV": mean_e,
                    "spectrum": spec,
                }
                print(f"  OK  nu_d={nu_d:.6e}  <E>={mean_e:.4f} MeV")
            else:
                print(f"  SKIP: unexpected data shape (spec len={len(spec)})")
        time.sleep(0.1)  # be polite
    return results

def emit_c_header(results, outpath):
    lines = []
    lines.append("/*")
    lines.append(" * gef_sf_spectra.h")
    lines.append(" *")
    lines.append(" * GEF-derived delayed neutron energy spectra for spontaneous fission.")
    lines.append(" * Generated by fetch_gef_spectra.py from:")
    lines.append(" *   https://github.com/tonyjnel/sf-delayed-neutron-data")
    lines.append(" *")
    lines.append(" * Source: T.J. Nel, sf-delayed-neutron-data (2025).")
    lines.append(" *   GEF version 2025/V1.2 (Schmidt & Jurado).")
    lines.append(" *   Spectra: composite evaporation model over GEF fission fragment yields.")
    lines.append(" *   200 bins, 0.05 MeV/bin, 0-10 MeV.  Probability density [1/MeV].")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef GEF_SF_SPECTRA_H")
    lines.append("#define GEF_SF_SPECTRA_H")
    lines.append("")
    lines.append("#define GEF_SF_NBIN    200")
    lines.append("#define GEF_SF_BIN_WIDTH  0.05   /* MeV per bin */")
    lines.append("#define GEF_SF_E_MIN   0.025  /* centre of first bin [MeV] */")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("   int    ZA;           /* 1000*Z + A */")
    lines.append("   double nu_d;         /* delayed neutrons per fission (GEF 2025/V1.2) */")
    lines.append("   double spectrum[GEF_SF_NBIN]; /* probability density [1/MeV] */")
    lines.append("} GEFSFSpectrum;")
    lines.append("")
    lines.append("static const GEFSFSpectrum gef_sf_table[] = {")

    for za in sorted(results.keys()):
        r = results[za]
        label = r["label"]
        nu_d = r["nu_d"]
        nu_d_unc = r["nu_d_unc"]
        mean_e = r["mean_E_MeV"]
        spec = r["spectrum"]
        lines.append(f"  /* {label} (ZA={za})  nu_d={nu_d:.6e} +/- {nu_d_unc:.2e}"
                     f"  <E>={mean_e:.4f} MeV */")
        lines.append(f"  {{ {za}, {nu_d:.8e},")
        lines.append("    {")
        # 5 values per line
        for i in range(0, NBIN, 5):
            chunk = spec[i:i+5]
            row = ", ".join(f"{v:.8e}" for v in chunk)
            comma = "," if i + 5 < NBIN else ""
            lines.append(f"      {row}{comma}")
        lines.append("    }},")

    lines.append("};")
    lines.append("")
    lines.append(f"#define GEF_SF_NENTRIES  "
                 f"((int)(sizeof(gef_sf_table)/sizeof(gef_sf_table[0])))")
    lines.append("")
    lines.append("/* Returns pointer to GEFSFSpectrum for given ZA, or NULL if not tabulated. */")
    lines.append("static const GEFSFSpectrum* find_gef_sf_spectrum(int za) {")
    lines.append("   for (int i = 0; i < GEF_SF_NENTRIES; i++)")
    lines.append("      if (gef_sf_table[i].ZA == za) return &gef_sf_table[i];")
    lines.append("   return NULL;")
    lines.append("}")
    lines.append("")
    lines.append("/*")
    lines.append(" * Sample a delayed neutron energy from the GEF tabulated spectrum")
    lines.append(" * using inverse-CDF.  u is a uniform [0,1) variate.")
    lines.append(" */")
    lines.append("static double smpGEFSFEnergy(const GEFSFSpectrum* sp, double u) {")
    lines.append("   double cdf = 0.0;")
    lines.append("   for (int i = 0; i < GEF_SF_NBIN; i++) {")
    lines.append("      cdf += sp->spectrum[i] * GEF_SF_BIN_WIDTH;")
    lines.append("      if (u <= cdf)")
    lines.append("         return GEF_SF_E_MIN + i * GEF_SF_BIN_WIDTH;")
    lines.append("   }")
    lines.append("   return GEF_SF_E_MIN + (GEF_SF_NBIN - 1) * GEF_SF_BIN_WIDTH;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* GEF_SF_SPECTRA_H */")

    with open(outpath, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nWrote {outpath} ({len(results)} isotopes)")

if __name__ == "__main__":
    import os
    outdir = os.path.dirname(os.path.abspath(__file__))

    results = fetch_all()
    if not results:
        print("ERROR: no data fetched", file=sys.stderr)
        sys.exit(1)

    json_path = os.path.join(outdir, "gef_sf_spectra.json")
    with open(json_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Wrote {json_path}")

    h_path = os.path.join(outdir, "gef_sf_spectra.h")
    emit_c_header(results, h_path)
